<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-06 at 11:09:24.
 */
class BestellingenTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Bestellingen
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Bestellingen;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Bestellingen::HaalBestellingOp
     * @todo   Implement testHaalBestellingOp().
     */
    public function testHaalBestellingOp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bestellingen::BestaatKenmerk
     * @todo   Implement testBestaatKenmerk().
     */
    public function testBestaatKenmerk() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bestellingen::UpdateKenmerk
     * @todo   Implement testUpdateKenmerk().
     */
    public function testUpdateKenmerk() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bestellingen::BestellingStatusIDForStatus
     * @todo   Implement testBestellingStatusIDForStatus().
     */
    public function testBestellingStatusIDForStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bestellingen::MaakBestellingAan
     * @todo   Implement testMaakBestellingAan().
     */
    public function testMaakBestellingAan() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bestellingen::BestellingStatusVoorID
     * @todo   Implement testBestellingStatusVoorID().
     */
    public function testBestellingStatusVoorID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Bestellingen::SlaStatusOp
     * @todo   Implement testSlaStatusOp().
     */
    public function testSlaStatusOp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
